### ISSUE TITLE
Installing 0.3.2 on windows produces an error

### ISSUE THREAD

**Issue by drozzy** [thruflo/pyramid_basemodel#10]
Complete output from command c:\Users\drozdyuka\Projects\LPSS\env-1092\Scrip
ts\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\drozdy~1\\app
data\\local\\temp\\pip-build-esnblr\\pyramid-basemodel\\setup.py';exec(compile(g
etattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__,
 'exec'))" install --record c:\users\drozdy~1\appdata\local\temp\pip-mojzdh-reco
rd\install-record.txt --single-version-externally-managed --compile --install-he
aders c:\Users\drozdyuka\Projects\LPSS\env-1092\include\site\python2.7\pyramid-b
asemodel: for pastedeploy==1.5.2
    running installploy 1.5.2
    running buildeploy-1.5.2-py2.7.egg
    running build_py already the active version in easy-install.pth
    creating build
    creating build\libka\projects\lpss\env-1092\lib\site-packages\pastedeploy-1.
    creating build\lib\pyramid_basemodel
    copying src\pyramid_basemodel\blob.py -> build\lib\pyramid_basemodel
    copying src\pyramid_basemodel\container.py -> build\lib\pyramid_basemodel
    copying src\pyramid_basemodel\interfaces.py -> build\lib\pyramid_basemodel
    copying src\pyramid_basemodel\mixin.py -> build\lib\pyramid_basemodel
    copying src\pyramid_basemodel\root.py -> build\lib\pyramid_basemodel
    copying src\pyramid_basemodel\slug.py -> build\lib\pyramid_basemodelationstr
    copying src\pyramid_basemodel\tree.py -> build\lib\pyramid_basemodel
    copying src\pyramid_basemodel\util.py -> build\lib\pyramid_basemodel
    copying src\pyramid_basemodel\__init__.py -> build\lib\pyramid_basemodel
    running egg_info1.0-py2.7.egg
    writing requirements to src\pyramid_basemodel.egg-info\requires.txt
    writing src\pyramid_basemodel.egg-info\PKG-INFO
    writing top-level names to src\pyramid_basemodel.egg-info\top_level.txt1.0-p
    writing dependency_links to src\pyramid_basemodel.egg-info\dependency_links.
txtrching for zope.deprecation==4.1.2
    warning: manifest_maker: standard file '-c' not found
    essing zope.deprecation-4.1.2-py2.7.egg
    reading manifest file 'src\pyramid_basemodel.egg-info\SOURCES.txt'th
    Traceback (most recent call last):
      File "<string>", line 1, in <module>-1092\lib\site-packages\zope.deprecati
      File "c:\users\drozdy~1\appdata\local\temp\pip-build-esnblr\pyramid-basemo
del\setup.py", line 59, in <module>
        install_requires=requirements
      File "c:\Python27\Lib\distutils\core.py", line 151, in setup
        dist.run_commands()active version in easy-install.pth
      File "c:\Python27\Lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)ects\lpss\env-1092\lib\site-packages\webob-1.4.1-py
      File "c:\Python27\Lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()==0.2.5
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\install.py", line 61, in runh file
        return orig.install.run(self)
      File "c:\Python27\Lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\Python27\Lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\Python27\Lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()uka\projects\lpss\env-1092\lib\site-packages
      File "c:\Python27\Lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\Python27\Lib\distutils\cmd.py", line 326, in run_commandSSAGES\\C
        self.distribution.run_command(command)
      File "c:\Python27\Lib\distutils\dist.py", line 972, in run_commandork.po'
        cmd_obj.run()ocale\\en\\LC_MESSAGES\\CommonFramework.mo'
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\build_py.py", line 47, in run
        self.build_package_data()k/locale\\fr\\LC_MESSAGES\\CommonFramework.po'
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\build_py.py", line 103, in build_package_data
        for package, src_dir, build_dir, filenames in self.data_files:e\\en\\LC_
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\build_py.py", line 59, in __getattr__ale\\en\\LC_MESSAGES\\PersonalLe
        self.data_files = files = self._get_data_files()\\en\\LC_MESSAGES\\Perso
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\build_py.py", line 72, in _get_data_filesrningassistant/locale\\fr\\L
        self.analyze_manifest()istant.po'
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\build_py.py", line 123, in analyze_manifestle\\fr\\LC_MESSAGES\\Perso
        self.run_command('egg_info')
      File "c:\Python27\Lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\Python27\Lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()ase
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\egg_info.py", line 180, in run
        self.find_sources()
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\egg_info.py", line 207, in find_sources
        mm.run()ATABASE =====
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\egg_info.py", line 291, in run
        self.add_defaults()
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\egg_info.py", line 327, in add_defaults
        self.read_manifest()ed, ignoring the state of the harvester.
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\sdist.py", line 196, in read_manifest
        self.filelist.append(line)
      File "c:\Users\drozdyuka\Projects\LPSS\env-1092\lib\site-packages\setuptoo
ls\command\egg_info.py", line 232, in append
        path = convert_path(item)
      File "c:\Python27\Lib\distutils\util.py", line 124, in convert_path
        raise ValueError, "path '%s' cannot be absolute" % pathnameFile|✚ 1…402]
    ValueError: path '/Users/thruflo/Development/pyramid/basemodel/CHANGES.md' c
annot be absolute

    ---------------

**Comment by thruflo** [comment]
Hmm, yes, seems to have a .egg-info folder in src.  That shouldn't be there.

**Comment by thruflo** [comment]
Try https://pypi.python.org/pypi/pyramid_basemodel/0.3.4

**Comment by drozzy** [comment]
Works, thanks!
